### ISSUE TITLE
抽象方法和实现方法的名字被混淆成了不同的字符串

### ISSUE THREAD

**Issue by coderstory** [lqs1848/AllatoriCrack#2]
实现类
```
public final class preferencesProvider extends PreferencesProvider {
    public /* synthetic */ String oooOoO() {
        return "com.coderstory.flyme.preferencesProvider";
    }
}
```

父类
```
public abstract class PreferencesProvider extends ContentProvider {

    public abstract /* synthetic */ String xXxXXX();
}

```

 导致的异常
```
02-22 17:20:55.985  3477  3477 E AndroidRuntime: java.lang.AbstractMethodError: abstract method "java.lang.String com.coderstory.flyme.preferences.PreferencesProvider.xXxXXX()"
```

原版没这个问题

**Comment by coderstory** [comment]
<config>
    <input>
        <dir in="${classesRoot}" out="${classesRoot}-obfuscated" />
        
        
    </input>

    <classpath>
        <jar name="${androidJar}" />
        <jar name="${classpathJars}" />
    </classpath>

    <keep-names>
        <class template="public class * instanceof android.app.Activity">
            <method template="public void *(android.view.View)" />
        </class>
        <class template="public class * instanceof android.view.View">
            <method template="void set*(**)" />
            <method template="get*()" />
        </class>
        <class template="class * extends java.lang.Enum">
            <method template="values()" />
            <method template="valueOf(java.lang.String)" />
        </class>
        <class template="class * implements android.os.Parcelable">
            <field template="public static final android.os.Parcelable*Creator *" />
        </class>
        <class template="class *.R*">
            <field template="public static *" />
        </class>
        <class template="public class * instanceof android.app.Application" />
        <class template="public class * instanceof android.app.Service" />
        <class template="public class com.coderstory.flyme.plugins.start" />
        <class template="public class com.coderstory.flyme.activity.MainActivity">
            <method template="isEnable()" />
        </class>
        <class template="public class com.coderstory.flyme.preferences.PreferencesProvider">
            <method template="getAuthorities()" />
        </class>
        <class template="public class com.coderstory.flyme.preferencesProvider">
            <method template="getAuthorities()" />
        </class>
        <class template="public class * instanceof android.content.BroadcastReceiver" />
        <class template="public class * instanceof android.content.ContentProvider" />
        <class template="public class * instanceof android.app.backup.BackupAgentHelper" />
        <class template="public class * instanceof android.preference.Preference" />
        <class template="public class com.android.vending.licensing.ILicensingService" />
        <class template="public class com.google.android.vending.licensing.ILicensingService" />
    </keep-names>
    <property name="extensive-flow-obfuscation" value="maximum" />
    <property name="string-encryption" value="maximum-with-warnings" />
    <property name="string-encryption-type" value="strong" />
    <property name="default-package" value="" />
    <property name="force-default-package" value="enable" />
    <property name="update-resource-names" value="enable" />
    <property name="inner-classes" value="remove" />
    <property name="finalize" value="enable" />
    <property name="generics" value="remove" />
    <property name="random-seed" value="wqeqweqweqw qweqwe11111" />
    <property name="update-resource-contents" value="enable" />
    <property name="update-resource-contents" value="enable:UTF-8" />
    <property name="remove-calls" value="android.util.Log.*" />
    <property name="log-file" value="${logFile}" />
    <property name="synthetize-methods" value="all" />
    <property name="control-flow-obfuscation" value="enable" />
    <property name="synthetize-fields" value="all" />
</config>

整个配置

**Comment by coderstory** [comment]
配置里的getAuthorities是后来加的。。。但是这种错误非常多 导致无法使用

**Comment by lqs1848** [comment]
更新了 你再试一下

**Comment by coderstory** [comment]
解决了 ~~
